import {AUTH_SERVER_AUTHENTICATION_TYPE} from '../enumerate.ts'

export const AUTH_SERVER_AUTHENTICATION_TYPE_PARAM = 'authenticationType'

export const AUTHENTICATION_MEMBER_TYPE: ReadonlyArray<string> = [
  AUTH_SERVER_AUTHENTICATION_TYPE.ENTERPRISE,
  AUTH_SERVER_AUTHENTICATION_TYPE.PERSONAL,
]
