import {USER_CHAT_CALL_PARTICIPANT_STATUS, USER_CHAT_PARTICIPANT_TYPE,} from '../enumerate/chat.ts'

export const USER_CHAT_PARTICIPANT_OWNER_TYPE_VALUE: ReadonlyArray<number> = [
  USER_CHAT_PARTICIPANT_TYPE.OWNER,
  USER_CHAT_PARTICIPANT_TYPE.CO_OWNER,
]

export const USER_CHAT_CALL_PARTICIPANT_ERROR_STATUS_VALUE: ReadonlyArray<number> = [
  USER_CHAT_CALL_PARTICIPANT_STATUS.COMPLETED,
  USER_CHAT_CALL_PARTICIPANT_STATUS.REJECTED,
  USER_CHAT_CALL_PARTICIPANT_STATUS.CANCELED,
  USER_CHAT_CALL_PARTICIPANT_STATUS.DIS_CONNECTION,
]

export const USER_CHAT_CALL_PARTICIPANT_PROCESSING_STATUS_VALUE: ReadonlyArray<number> = [
  USER_CHAT_CALL_PARTICIPANT_STATUS.INITIATING,
  USER_CHAT_CALL_PARTICIPANT_STATUS.RINGING,
  USER_CHAT_CALL_PARTICIPANT_STATUS.CONNECTING,
]

export const CHAT_EVERYONE_ID = 'EVERYONE'
