import {
    MESSAGE_SERVER_USER_CHAT_CALL_PARTICIPANT_STATUS,
    MESSAGE_SERVER_USER_CHAT_PARTICIPANT_TYPE,
} from '../enumerate.ts'

export const USER_CHAT_PARTICIPANT_OWNER_TYPE_VALUE: ReadonlyArray<number> = [
  MESSAGE_SERVER_USER_CHAT_PARTICIPANT_TYPE.OWNER,
  MESSAGE_SERVER_USER_CHAT_PARTICIPANT_TYPE.CO_OWNER,
]

export const USER_CHAT_CALL_PARTICIPANT_ERROR_STATUS_VALUE: ReadonlyArray<number> = [
  MESSAGE_SERVER_USER_CHAT_CALL_PARTICIPANT_STATUS.COMPLETED,
  MESSAGE_SERVER_USER_CHAT_CALL_PARTICIPANT_STATUS.REJECTED,
  MESSAGE_SERVER_USER_CHAT_CALL_PARTICIPANT_STATUS.CANCELED,
  MESSAGE_SERVER_USER_CHAT_CALL_PARTICIPANT_STATUS.DIS_CONNECTION,
]

export const USER_CHAT_CALL_PARTICIPANT_PROCESSING_STATUS_VALUE: ReadonlyArray<number> = [
  MESSAGE_SERVER_USER_CHAT_CALL_PARTICIPANT_STATUS.INITIATING,
  MESSAGE_SERVER_USER_CHAT_CALL_PARTICIPANT_STATUS.RINGING,
  MESSAGE_SERVER_USER_CHAT_CALL_PARTICIPANT_STATUS.CONNECTING,
]

export const CHAT_EVERYONE_ID = 'EVERYONE'
