export const OPERATION_DATA_TRACE_TABLE = {
  DICTIONARY_TYPE: 'tb_dictionary_type',
  DATA_DICTIONARY: 'tb_data_dictionary',
  CAROUSEL: 'tb_carousel',
  SMS_MESSAGE: 'tb_sms_message',
  SITE_MESSAGE: 'tb_site_message',
  EMAIL_MESSAGE: 'tb_email_message',
  ROLE: 'tb_role',
  ENTERPRISE_ROLE: 'tb_enterprise_role',
  RESOURCE: 'tb_resource',
  CONSOLE_USER: 'tb_console_user',
  ENTERPRISE_MEMBER: 'tb_enterprise_member',
  AI_MODEL_SETTING: 'tb_ai_model_setting',
  AI_MCP_PACKAGE: 'tb_ai_mcp_package',
  AI_SKILL_PACKAGE: 'tb_ai_skill_package',
  ENTERPRISE: 'tb_enterprise',
  PERSONAL_USER: 'tb_personal_user',
  ENTERPRISE_INVITATION: 'tb_enterprise_invitation',
} as const
