import {
  AGENT_BLOCK_STATUS,
  AGENT_CHAT_STATUS,
  AGENT_CONTENT_TYPE,
  AGENT_CONVERSATION_TYPE,
  AGENT_TOOL_BLOCK_STATUS,
} from '../enumerate/agent.ts'
import {MCP_CLIENT_TYPE} from '../enumerate/mcp.ts'

export const BLOCK_RUNNING_STATUS_VALUE: ReadonlyArray<string> = [
  AGENT_BLOCK_STATUS.READY,
  AGENT_BLOCK_STATUS.PENDING,
  AGENT_BLOCK_STATUS.RUNNING,
]

export const STREAM_RUNNING_STATUS_VALUE: ReadonlyArray<number> = [
  AGENT_CHAT_STATUS.READY,
  AGENT_CHAT_STATUS.RUNNING,
]

export const AGENT_WORKSPACE_TYPE_VALUE: ReadonlyArray<number> = [
  AGENT_CONVERSATION_TYPE.DEFAULT_WORKSPACE,
  AGENT_CONVERSATION_TYPE.CUSTOMIZE_WORKSPACE,
]

export const AGENT_TOOL_BLOCK_CONFIRM_STATUS_VALUE: ReadonlyArray<string> = [
  AGENT_TOOL_BLOCK_STATUS.PENDING,
  AGENT_TOOL_BLOCK_STATUS.ASKING,
]

export const MCP_CLIENT_HTTP_TYPE_VALUE: ReadonlyArray<string> = [
  MCP_CLIENT_TYPE.SSE,
  MCP_CLIENT_TYPE.STREAMABLE_HTTP,
]

export const STREAM_APPEND_TYPES: ReadonlyArray<(typeof AGENT_CONTENT_TYPE)[keyof typeof AGENT_CONTENT_TYPE]> = [
  AGENT_CONTENT_TYPE.THINK,
  AGENT_CONTENT_TYPE.ANSWER,
  AGENT_CONTENT_TYPE.ERROR,
  AGENT_CONTENT_TYPE.TOOL,
]

export const UPDATE_CONVERSATION_TYPES: ReadonlyArray<(typeof AGENT_CONTENT_TYPE)[keyof typeof AGENT_CONTENT_TYPE]> = [
  AGENT_CONTENT_TYPE.AGENT_STATUS_CHANGE,
  AGENT_CONTENT_TYPE.GENERATE_CONVERSATION_NAME,
]
