import {
  AI_SERVER_AGENT_BLOCK_STATUS,
  AI_SERVER_AGENT_CHAT_STATUS,
  AI_SERVER_AGENT_CONTENT_TYPE,
  AI_SERVER_AGENT_CONVERSATION_TYPE,
  AI_SERVER_AGENT_TOOL_BLOCK_STATUS,
  AI_SERVER_MCP_CLIENT_TYPE,
} from '../enumerate.ts'

export const BLOCK_RUNNING_STATUS_VALUE: ReadonlyArray<string> = [
  AI_SERVER_AGENT_BLOCK_STATUS.READY,
  AI_SERVER_AGENT_BLOCK_STATUS.PENDING,
  AI_SERVER_AGENT_BLOCK_STATUS.RUNNING,
]

export const STREAM_RUNNING_STATUS_VALUE: ReadonlyArray<number> = [
  AI_SERVER_AGENT_CHAT_STATUS.READY,
  AI_SERVER_AGENT_CHAT_STATUS.RUNNING,
]

export const AGENT_WORKSPACE_TYPE_VALUE: ReadonlyArray<number> = [
  AI_SERVER_AGENT_CONVERSATION_TYPE.DEFAULT_WORKSPACE,
  AI_SERVER_AGENT_CONVERSATION_TYPE.CUSTOMIZE_WORKSPACE,
]

export const AGENT_TOOL_BLOCK_CONFIRM_STATUS_VALUE: ReadonlyArray<string> = [
  AI_SERVER_AGENT_TOOL_BLOCK_STATUS.PENDING,
  AI_SERVER_AGENT_TOOL_BLOCK_STATUS.ASKING,
]

export const MCP_CLIENT_HTTP_TYPE_VALUE: ReadonlyArray<string> = [
  AI_SERVER_MCP_CLIENT_TYPE.SSE,
  AI_SERVER_MCP_CLIENT_TYPE.STREAMABLE_HTTP,
]

export const STREAM_APPEND_TYPES: ReadonlyArray<(typeof AI_SERVER_AGENT_CONTENT_TYPE)[keyof typeof AI_SERVER_AGENT_CONTENT_TYPE]> = [
  AI_SERVER_AGENT_CONTENT_TYPE.THINK,
  AI_SERVER_AGENT_CONTENT_TYPE.ANSWER,
  AI_SERVER_AGENT_CONTENT_TYPE.ERROR,
  AI_SERVER_AGENT_CONTENT_TYPE.TOOL,
]

export const UPDATE_CONVERSATION_TYPES: ReadonlyArray<(typeof AI_SERVER_AGENT_CONTENT_TYPE)[keyof typeof AI_SERVER_AGENT_CONTENT_TYPE]> = [
  AI_SERVER_AGENT_CONTENT_TYPE.AGENT_STATUS_CHANGE,
  AI_SERVER_AGENT_CONTENT_TYPE.GENERATE_CONVERSATION_NAME,
]
