export {default} from './CrudConfigProvider'
export type {CrudConfigProviderProps, CrudConfigProviderSlots} from './CrudConfigProvider'
export {useActionAuth, useCrudConfig} from './useCrudConfig'
export {CRUD_CONFIG_KEY} from './types'
export type {CrudConfig} from './types'
